[versions]
springBoot = "4.1.0"
springAi = "2.0.0"
springDependencyManagement = "1.1.7"

[libraries]
spring-ai-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "springAi" }
spring-ai-openai = { module = "org.springframework.ai:spring-ai-openai" }
spring-ai-client-chat = { module = "org.springframework.ai:spring-ai-client-chat" }
spring-ai-starter-model-openai = { module = "org.springframework.ai:spring-ai-starter-model-openai" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
